"""Англоязычные обучающие примеры для классификатора формул.

Основной набор написан по-русски. Многоязычная модель переносит смысл между
языками сама, но признаки, считающие ключевые слова, на английском тексте
срабатывают по другим основам, и без собственных примеров модель видела бы их
только на распознавании. Записи формул те же, что в русской части: меняется
окружающий текст, потому что именно он несёт язык.
"""

DATA = [
    # === MATH ===
    ['math', r'f(x) = ax^2 + bx + c', 'quadratic function equation root value'],
    ['math', r'\sum_{i=1}^n x_i', 'sum index limit iteration series'],
    ['math', r'\int_a^b f(x) dx', 'definite integral area computation'],
    ['math', r'P(A) = m/n', 'probability event statistics outcome'],
    ['math', r'\sin \alpha + \cos \beta', 'trigonometry angle function identity'],
    ['math', r'A \cdot B = C', 'matrix vector multiplication product'],
    ['math', r'\lim_{n \to \infty}', 'limit infinity sequence convergence'],
    ['math', r'\frac{dy}{dx}', 'derivative differential function slope'],
    ['math', r'(a + b)^2 = a^2 + 2ab + b^2', 'square of a sum algebraic identity'],
    ['math', r'(a - b)^2 = a^2 - 2ab + b^2', 'square of a difference algebraic identity'],
    ['math', r'\frac{6 \cdot 10^{8}}{143} \approx 4 \cdot 10^{6}', 'substituting numerical values final estimate ratio'],
    ['math', r'w = \frac{m_{pract}}{m_{theor}} \cdot 100 \%', 'yield defined as the ratio of practical to theoretical mass'],
    ['math', r'\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i', 'arithmetic mean of a sample statistics'],
    ['math', r's^2 = \frac{1}{n-1}\sum (x_i - \bar{x})^2', 'sample variance dispersion statistics'],
    ['math', r'y = kx + b', 'linear function straight line coefficient'],
    ['math', r'\log_a b = \frac{\ln b}{\ln a}', 'logarithm change of base'],
    ['math', r'D = b^2 - 4ac', 'discriminant of the quadratic equation'],
    ['math', r'C_n^k = \frac{n!}{k!(n-k)!}', 'combinations binomial coefficient'],
    ['math', r'\det(A - \lambda E) = 0', 'characteristic equation eigenvalue matrix'],
    ['math', r'a_n = a_1 + (n-1)d', 'arithmetic progression term formula'],
    ['math', r'\nabla f = \left(\frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}\right)', 'gradient of a scalar function partial derivative'],
    ['math', r'V = \frac{4}{3}\pi R^3', 'volume of a sphere geometry'],
    ['math', r'S = \pi R^2', 'area of a circle geometry'],
    ['math', r'\varepsilon = \frac{\Delta l}{l_0}', 'relative elongation ratio dimensionless'],
    ['math', r'k = \frac{d_{\max}}{d_{\min}}', 'ratio of the largest to the smallest diameter'],
    ['math', r'x_{1,2} = \frac{-b \pm \sqrt{D}}{2a}', 'roots of the quadratic equation'],
    ['math', r'\tan \theta = \frac{\sin \theta}{\cos \theta}', 'tangent trigonometric identity'],
    ['math', r'f\'(x) = \lim_{h \to 0}\frac{f(x+h)-f(x)}{h}', 'definition of the derivative limit'],
    ['math', r'n! = n \cdot (n-1)!', 'factorial recurrence definition'],
    ['math', r'\mu = \frac{\sum n_i x_i}{\sum n_i}', 'weighted average estimate of a coefficient'],

    # === PHYSICS ===
    ['physics', r'\sigma = E \varepsilon', 'Hooke law relates stress to strain through the elastic modulus'],
    ['physics', r'Q = m c \Delta T', 'heat required to raise the temperature specific heat capacity'],
    ['physics', r'F = ma', 'Newton second law force mass acceleration'],
    ['physics', r'E = mc^2', 'mass energy equivalence rest energy'],
    ['physics', r'p = \frac{F}{S}', 'pressure force per unit area'],
    ['physics', r'\sigma = \frac{F}{A}', 'normal stress in the cross section of a bar'],
    ['physics', r'\tau = \frac{M_k}{W_p}', 'shear stress under torsion torque'],
    ['physics', r'A = F s \cos \alpha', 'mechanical work done by a force displacement'],
    ['physics', r'N = \frac{A}{t}', 'power as work per unit time'],
    ['physics', r'\rho = \frac{m}{V}', 'density mass per unit volume'],
    ['physics', r'I = \frac{U}{R}', 'Ohm law current voltage resistance'],
    ['physics', r'P = UI', 'electric power voltage current'],
    ['physics', r'v = v_0 + at', 'uniformly accelerated motion velocity time'],
    ['physics', r'E_k = \frac{mv^2}{2}', 'kinetic energy of a moving body'],
    ['physics', r'E_p = mgh', 'potential energy in a gravitational field'],
    ['physics', r'\lambda = \frac{Q}{S \Delta T} \delta', 'thermal conductivity heat flow through a wall'],
    ['physics', r'\varepsilon_{\Sigma} = \frac{h_0 - h_n}{h_0}', 'total reduction during rolling deformation'],
    ['physics', r'\eta = \frac{A_{use}}{A_{full}} \cdot 100 \%', 'efficiency of a machine ratio of useful work'],
    ['physics', r'\sigma_t = \frac{P}{F_0}', 'tensile strength of the specimen under load'],
    ['physics', r'HB = \frac{2P}{\pi D (D - \sqrt{D^2 - d^2})}', 'Brinell hardness indentation test'],
    ['physics', r'\Delta l = \alpha l_0 \Delta T', 'thermal expansion of a rod temperature'],
    ['physics', r'M_k = F r', 'torque applied to the shaft moment of force'],
    ['physics', r'\omega = 2\pi n', 'angular velocity rotation frequency'],
    ['physics', r'G = \frac{E}{2(1+\mu)}', 'shear modulus Poisson ratio elastic constants'],
    ['physics', r'\sigma_{-1} = 0.43 \sigma_t', 'fatigue limit endurance strength estimate'],
    ['physics', r'q = -\lambda \frac{dT}{dx}', 'Fourier law of heat conduction flux'],
    ['physics', r'\nu = \frac{\eta}{\rho}', 'kinematic viscosity of the melt'],
    ['physics', r'K_{Ic} = \sigma \sqrt{\pi a}', 'fracture toughness stress intensity factor crack'],
    ['physics', r'\varepsilon = \frac{\sigma}{E} + \varepsilon_{pl}', 'total strain elastic and plastic components'],
    ['physics', r'W = \int_0^{\varepsilon} \sigma \, d\varepsilon', 'specific work of plastic deformation'],

    # === CHEMISTRY ===
    ['chemistry', r'Fe_2O_3 + 3CO = 2Fe + 3CO_2', 'reduction of iron ore carbon monoxide reducing agent'],
    ['chemistry', r'C + CO_2 = 2CO', 'Boudouard reaction direct reduction by solid carbon'],
    ['chemistry', r'FeS + CaO + C = CaS + Fe + CO', 'desulphurisation in the hearth lime reacts with ferrous sulphide'],
    ['chemistry', r'2H_2 + O_2 = 2H_2O', 'combustion of hydrogen water formation reaction'],
    ['chemistry', r'CaCO_3 = CaO + CO_2', 'thermal decomposition of limestone calcination'],
    ['chemistry', r'TiCl_4 + 2Mg = Ti + 2MgCl_2', 'magnesium thermal reduction of titanium tetrachloride'],
    ['chemistry', r'2NH_4VO_3 = V_2O_5 + 2NH_3 + H_2O', 'thermal decomposition of ammonium metavanadate'],
    ['chemistry', r'Fe_3O_4 + CO = 3FeO + CO_2', 'stepwise reduction of magnetite in the shaft'],
    ['chemistry', r'2Al + Fe_2O_3 = Al_2O_3 + 2Fe', 'aluminothermic reaction thermite mixture'],
    ['chemistry', r'SiO_2 + 2C = Si + 2CO', 'carbothermic reduction of silica in the furnace'],
    ['chemistry', r'CH_4 + 2O_2 = CO_2 + 2H_2O', 'complete combustion of methane in the burner'],
    ['chemistry', r'Zn + H_2SO_4 = ZnSO_4 + H_2', 'zinc dissolves in dilute sulphuric acid'],
    ['chemistry', r'NaOH + HCl = NaCl + H_2O', 'neutralisation of an acid by an alkali salt'],
    ['chemistry', r'Cu^{2+} + 2e = Cu', 'cathodic half reaction electrolysis of copper'],
    ['chemistry', r'Fe = Fe^{2+} + 2e', 'anodic dissolution of iron corrosion'],
    ['chemistry', r'NO_3^- + 4H^+ + 3e = NO + 2H_2O', 'reduction of nitrate in acid medium half reaction'],
    ['chemistry', r'2Fe + 3/2 O_2 = Fe_2O_3', 'oxidation of iron scale formation'],
    ['chemistry', r'MnO + SiO_2 = MnSiO_3', 'slag formation manganese silicate'],
    ['chemistry', r'CaO + SiO_2 = CaSiO_3', 'basic oxide reacts with silica in the slag'],
    ['chemistry', r'[C] + [O] = CO', 'carbon oxygen reaction in the steel melt'],
    ['chemistry', r'N_2 + 3H_2 = 2NH_3', 'ammonia synthesis equilibrium catalyst'],
    ['chemistry', r'S + O_2 = SO_2', 'roasting of sulphide concentrate'],
    ['chemistry', r'2SO_2 + O_2 = 2SO_3', 'catalytic oxidation of sulphur dioxide equilibrium'],
    ['chemistry', r'Al_2O_3 = 2Al + 3/2 O_2', 'electrolysis of alumina in a cryolite bath'],
    ['chemistry', r'FeO + C = Fe + CO', 'direct reduction of wustite by solid carbon'],
    ['chemistry', r'Ti + 7HF - 5e = [TiF_7]^{2-} + 7H^+', 'anodic dissolution in fluoride electrolyte'],
    ['chemistry', r'Mg(OH)_2 = MgO + H_2O', 'dehydration of magnesium hydroxide on heating'],
    ['chemistry', r'2KMnO_4 = K_2MnO_4 + MnO_2 + O_2', 'decomposition of potassium permanganate'],
    ['chemistry', r'\Delta H = 2\Delta_f H(MgCl_2) - \Delta_f H(TiCl_4)', 'thermal effect of the reaction standard enthalpy of formation'],
    ['chemistry', r'n = \frac{m}{M}', 'amount of substance mole molar mass of the compound'],
]
